<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Gerardo Abarca" />

<meta name="date" content="2025-09-02" />

<title>Bellabeat Case Study</title>

<script src="bellabeat_markdown_files/header-attrs-2.29/header-attrs.js"></script>
<script src="bellabeat_markdown_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="bellabeat_markdown_files/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="bellabeat_markdown_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="bellabeat_markdown_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="bellabeat_markdown_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="bellabeat_markdown_files/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="bellabeat_markdown_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="bellabeat_markdown_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="bellabeat_markdown_files/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { color: #cccccc; background-color: #303030; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ffcfaf; } /* Alert */
code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #dca3a3; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #f0dfaf; } /* ControlFlow */
code span.ch { color: #dca3a3; } /* Char */
code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code span.co { color: #7f9f7f; } /* Comment */
code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code span.do { color: #7f9f7f; } /* Documentation */
code span.dt { color: #dfdfbf; } /* DataType */
code span.dv { color: #dcdccc; } /* DecVal */
code span.er { color: #c3bf9f; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #c0bed1; } /* Float */
code span.fu { color: #efef8f; } /* Function */
code span.im { } /* Import */
code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
code span.kw { color: #f0dfaf; } /* Keyword */
code span.op { color: #f0efd0; } /* Operator */
code span.ot { color: #efef8f; } /* Other */
code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code span.sc { color: #dca3a3; } /* SpecialChar */
code span.ss { color: #cc9393; } /* SpecialString */
code span.st { color: #cc9393; } /* String */
code span.va { } /* Variable */
code span.vs { color: #cc9393; } /* VerbatimString */
code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">



<h1 class="title toc-ignore">Bellabeat Case Study</h1>
<h4 class="author">Gerardo Abarca</h4>
<h4 class="date">2025-09-02</h4>

</div>


<div id="bellabeat" class="section level3">
<h3>Bellabeat</h3>
<p>This case study explores how <strong>Bellabeat</strong>, a high-tech
company that manufactures health-focused smart products for women, can
improve its performance and marketing strategy. By analyzing publicly
available smart device usage data (e.g., Fitbit), we aim to understand
how consumers interact with non-Bellabeat devices.</p>
<p>The insights derived from this analysis will be applied to
Bellabeat’s product portfolio to identify opportunities for growth,
optimize marketing campaigns, and strengthen the company’s position in
the global wellness technology market.</p>
<p>This project follows six key steps that guide the completion of the
case study:</p>
<ol style="list-style-type: decimal">
<li><strong>Ask</strong> – Define the business problem and
objectives.<br />
</li>
<li><strong>Prepare</strong> – Collect and organize the necessary
data.<br />
</li>
<li><strong>Process</strong> – Clean and structure the data for
analysis.<br />
</li>
<li><strong>Analyze</strong> – Identify trends, patterns, and
insights.<br />
</li>
<li><strong>Share</strong> – Communicate findings through reports and
visualizations.<br />
</li>
<li><strong>Act</strong> – Apply insights to support business decisions
and strategies.</li>
</ol>
<hr />
</div>
<div id="ask" class="section level2">
<h2>💡 Ask</h2>
<p>The goal of this phase is to define the business problem, identify
key stakeholders, and clarify the business task.</p>
<div id="guiding-questions" class="section level4">
<h4>Guiding Questions</h4>
<ul>
<li><p><strong>What is the problem you are trying to
solve?</strong><br />
Bellabeat wants to understand how customers use smart devices (e.g.,
Fitbit) in order to identify usage trends. The aim is to apply these
insights to one of Bellabeat’s products and improve its marketing
strategy, ultimately supporting the company’s expansion in the global
wellness technology market.</p></li>
<li><p><strong>How can your insights drive business
decisions?</strong><br />
The insights will highlight customer behavior patterns (e.g., activity
levels, sleep tracking, daily steps). These findings can inform targeted
marketing campaigns, refine product positioning, and identify growth
opportunities by aligning Bellabeat’s offerings with what users value
most in wellness technology.</p></li>
</ul>
</div>
<div id="key-tasks" class="section level4">
<h4>Key Tasks</h4>
<ol style="list-style-type: decimal">
<li><strong>Identify the business task</strong>
<ul>
<li>Analyze smart device usage data (Fitbit dataset) to identify
consumer behavior trends.<br />
</li>
<li>Apply insights to one Bellabeat product (Leaf, Time, Spring, or
Bellabeat App) and generate high-level marketing recommendations.</li>
</ul></li>
<li><strong>Consider key stakeholders</strong>
<ul>
<li><strong>Urška Sršen (Cofounder &amp; CCO):</strong> Wants actionable
insights that align with Bellabeat’s brand vision.<br />
</li>
<li><strong>Sando Mur (Cofounder):</strong> Interested in data-driven
strategies to support company growth.<br />
</li>
<li><strong>Marketing Analytics Team:</strong> Will use findings to
design and optimize campaigns.<br />
</li>
<li><strong>Executive Team:</strong> Decision-makers who will evaluate
recommendations and guide strategy.</li>
</ul></li>
</ol>
</div>
<div id="deliverable" class="section level4">
<h4>Deliverable</h4>
<p>The business task is to analyze smart device usage data from
non-Bellabeat products in order to identify consumer trends. These
insights will then be applied to one selected Bellabeat product to guide
marketing strategy, improve customer engagement, and support company
growth in the wellness technology market.</p>
<p>To achieve this, the <strong>next step is to prepare the
data</strong>, ensuring that it is collected, well-structured, and
relevant to our business task.</p>
<hr />
</div>
</div>
<div id="prepare" class="section level2">
<h2>📌 Prepare</h2>
<p>The goal of this phase is to gather the data, assess its quality, and
identify which parts of the dataset are relevant for the business
task.</p>
<div id="guiding-questions-1" class="section level4">
<h4>Guiding Questions</h4>
<ul>
<li><p><strong>Where is your dataset stored?</strong><br />
The dataset is stored on Kaggle and downloaded as a ZIP file containing
multiple CSVs.</p></li>
<li><p><strong>How is the data organized?</strong><br />
The dataset is a mix of wide-format files (daily summaries) and
long-format files (minute-level logs for steps, sleep, and heart
rate).</p></li>
<li><p><strong>Does your data ROCCC?</strong></p>
<ul>
<li><strong>Reliable:</strong> Limited reliability; users logged
different durations, and demographic data (e.g., age, gender) is
missing. Additionally, not all users logged all activities—some only
tracked steps, while others only tracked sleep or heart rate.<br />
</li>
<li><strong>Original:</strong> Secondary data collected via Amazon
Mechanical Turk participants, not a random sample of all Fitbit
users.<br />
</li>
<li><strong>Comprehensive:</strong> Covers activity, sleep, and heart
rate, but does not include hydration or stress metrics.<br />
</li>
<li><strong>Current:</strong> Data was collected in 2016, so it is
outdated for present-day behavior analysis.<br />
</li>
<li><strong>Cited:</strong> Provided by Möbius and available on Kaggle
under CC0 license.</li>
</ul></li>
<li><p><strong>What are the problems with the data?</strong><br />
The dataset is small (30 users), unevenly logged, and dated (2016). It
also lacks demographic information. These factors restrict
generalizability to the broader Bellabeat customer base.</p></li>
<li><p><strong>Licensing, privacy, security</strong><br />
The dataset is under a <strong>CC0: Public Domain license</strong>,
meaning it is free to use without restrictions.</p></li>
<li><p><strong>How did you verify the data’s integrity?</strong><br />
By inspecting the files for consistent structure, correct formatting,
and alignment with the Kaggle description.</p></li>
</ul>
</div>
<div id="key-tasks-1" class="section level4">
<h4>Key Tasks</h4>
<ol style="list-style-type: decimal">
<li><strong>Download the data</strong> → Retrieved from Kaggle and
stored locally in organized folders.<br />
</li>
<li><strong>Unzip and review files</strong> → Inspected CSVs to
understand their structure and variables.<br />
</li>
<li><strong>Filter the data</strong> → Identified datasets relevant to
the business task.<br />
</li>
<li><strong>Determine credibility</strong> → Evaluated the dataset using
the ROCCC framework.</li>
</ol>
</div>
<div id="selected-datasets-to-be-used" class="section level4">
<h4>Selected Datasets (to be used)</h4>
<ul>
<li><em>dailyActivity_merged.csv</em> → Summary of daily steps,
distance, calories, and activity minutes.<br />
</li>
<li><em>sleepDay_merged.csv</em> → Sleep records including duration and
efficiency.<br />
</li>
<li><em>hourlySteps_merged.csv</em> → Hourly step counts, indicating
movement patterns.<br />
</li>
<li><em>weightLogInfo_merged.csv</em> (optional) → Weight and BMI
logs.</li>
</ul>
<p><strong>Note</strong>: Hourly calories (hourlyCalories_merged.csv)
and hourly intensities (hourlyIntensities_merged.csv) were considered
but excluded, because:</p>
<ul>
<li>Daily totals from dailyActivity_merged.csv already capture overall
energy expenditure.</li>
<li>Daily active minutes provide sufficient insight into activity
intensity for high-level business recommendations.</li>
<li>Including these datasets would add granularity without materially
improving insights for the current business task.</li>
</ul>
</div>
<div id="datasets-not-selected-excluded-from-analysis"
class="section level4">
<h4>Datasets Not Selected (excluded from analysis)</h4>
<ul>
<li><em>heartrate_seconds_merged.csv</em> → Too granular; second-level
data not necessary for current business scope.<br />
</li>
<li><em>minute datasets (e.g., minuteStepsNarrow.csv,
minuteCaloriesWide.csv)</em> → High granularity, may add noise without
significant value.<br />
</li>
<li><em>Duplicated daily-level files</em> → Redundant, already captured
in dailyActivity_merged.csv.</li>
</ul>
</div>
<div id="deliverable-1" class="section level4">
<h4>Deliverable</h4>
<p>A curated collection of relevant Fitbit datasets, organized and
documented, ready for processing.</p>
</div>
<div id="transition-to-process" class="section level4">
<h4>Transition to Process</h4>
<p>With the dataset selected and scoped, the next step is to
<strong>prepare it for analysis</strong>. This involves checking data
quality, merging overlapping files, removing duplicates, and
transforming variables into consistent formats so that the data is
clean, reliable, and ready to explore.</p>
<hr />
</div>
</div>
<div id="process" class="section level2">
<h2>⚙️ Process</h2>
<div id="setup" class="section level4">
<h4>Setup</h4>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># Install packages (run once if needed)</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="co"># install.packages(&quot;tidyverse&quot;)</span></span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="co"># install.packages(&quot;readr&quot;)</span></span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="co"># install.packages(&quot;lubridate&quot;)</span></span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="co"># install.packages(&quot;dplyr&quot;)</span></span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="co"># install.packages(&quot;ggplot2&quot;)</span></span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="co"># install.packages(&quot;skimr&quot;)</span></span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a><span class="co"># install.packages(&quot;janitor&quot;)</span></span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a><span class="co"># install.packages(&quot;ggrepel&quot;)</span></span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ✔ purrr     1.1.0     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a><span class="fu">library</span>(hms)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;hms&#39;
## 
## The following object is masked from &#39;package:lubridate&#39;:
## 
##     hms</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;janitor&#39;
## 
## The following objects are masked from &#39;package:stats&#39;:
## 
##     chisq.test, fisher.test</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span></code></pre></div>
</div>
<div id="import-data-and-merge-datasets" class="section level4">
<h4>Import Data and Merge Datasets</h4>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="do">### Import Data and Merge Datasets</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a><span class="co"># Importing CSV files and cleaning column names right away</span></span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a>daily_activity_march_april <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;/cloud/project/march_april.16/Fitabase Data 3.12.16-4.11.16/dailyActivity_merged.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 457 Columns: 15
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (1): ActivityDate
## dbl (14): Id, TotalSteps, TotalDistance, TrackerDistance, LoggedActivitiesDi...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>daily_activity_april_may <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;/cloud/project/april_may.16/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv&quot;</span>) </span></code></pre></div>
<pre><code>## Rows: 940 Columns: 15
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (1): ActivityDate
## dbl (14): Id, TotalSteps, TotalDistance, TrackerDistance, LoggedActivitiesDi...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>sleep_day <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;/cloud/project/april_may.16/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv&quot;</span>) </span></code></pre></div>
<pre><code>## Rows: 413 Columns: 5
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (1): SleepDay
## dbl (4): Id, TotalSleepRecords, TotalMinutesAsleep, TotalTimeInBed
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>weight_log <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;/cloud/project/march_april.16/Fitabase Data 3.12.16-4.11.16/weightLogInfo_merged.csv&quot;</span>) </span></code></pre></div>
<pre><code>## Rows: 33 Columns: 8
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (1): Date
## dbl (6): Id, WeightKg, WeightPounds, Fat, BMI, LogId
## lgl (1): IsManualReport
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a>weight_log_two <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;/cloud/project/april_may.16/Fitabase Data 4.12.16-5.12.16/weightLogInfo_merged.csv&quot;</span>) </span></code></pre></div>
<pre><code>## Rows: 67 Columns: 8
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (1): Date
## dbl (6): Id, WeightKg, WeightPounds, Fat, BMI, LogId
## lgl (1): IsManualReport
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a>hourly_steps_march <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;/cloud/project/march_april.16/Fitabase Data 3.12.16-4.11.16/hourlySteps_merged.csv&quot;</span>) </span></code></pre></div>
<pre><code>## Rows: 24084 Columns: 3
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (1): ActivityHour
## dbl (2): Id, StepTotal
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a>hourly_steps_april <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;/cloud/project/april_may.16/Fitabase Data 4.12.16-5.12.16/hourlySteps_merged.csv&quot;</span>) </span></code></pre></div>
<pre><code>## Rows: 22099 Columns: 3
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (1): ActivityHour
## dbl (2): Id, StepTotal
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a><span class="co"># Merging datasets</span></span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a>daily_activity <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(daily_activity_march_april, daily_activity_april_may)</span>
<span id="cb22-3"><a href="#cb22-3" tabindex="-1"></a>weight_log_info <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(weight_log, weight_log_two)</span>
<span id="cb22-4"><a href="#cb22-4" tabindex="-1"></a>hourly_steps <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(hourly_steps_march, hourly_steps_april)</span>
<span id="cb22-5"><a href="#cb22-5" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" tabindex="-1"></a><span class="co"># Cleaning / Feature engineering</span></span>
<span id="cb22-7"><a href="#cb22-7" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" tabindex="-1"></a><span class="co"># Change data types</span></span>
<span id="cb22-9"><a href="#cb22-9" tabindex="-1"></a>daily_activity <span class="ot">&lt;-</span> daily_activity <span class="sc">%&gt;%</span></span>
<span id="cb22-10"><a href="#cb22-10" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ActivityDate =</span> <span class="fu">as.Date</span>(ActivityDate, <span class="at">format =</span> <span class="st">&quot;%m/%d/%Y&quot;</span>))</span>
<span id="cb22-11"><a href="#cb22-11" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" tabindex="-1"></a>sleep_day <span class="ot">&lt;-</span> sleep_day <span class="sc">%&gt;%</span></span>
<span id="cb22-13"><a href="#cb22-13" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SleepDay =</span> <span class="fu">as.Date</span>(SleepDay, <span class="at">format=</span> <span class="st">&quot;%m/%d/%Y %I:%M:%S %p&quot;</span>))</span>
<span id="cb22-14"><a href="#cb22-14" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" tabindex="-1"></a><span class="co"># Add sleep efficiency</span></span>
<span id="cb22-16"><a href="#cb22-16" tabindex="-1"></a>sleep_day <span class="ot">&lt;-</span> sleep_day <span class="sc">%&gt;%</span></span>
<span id="cb22-17"><a href="#cb22-17" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SleepEfficiency =</span> (TotalMinutesAsleep <span class="sc">/</span> TotalTimeInBed) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb22-18"><a href="#cb22-18" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" tabindex="-1"></a><span class="co"># Add activity level categories</span></span>
<span id="cb22-20"><a href="#cb22-20" tabindex="-1"></a>daily_activity <span class="ot">&lt;-</span> daily_activity <span class="sc">%&gt;%</span></span>
<span id="cb22-21"><a href="#cb22-21" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-22"><a href="#cb22-22" tabindex="-1"></a>    <span class="at">ActivityLevel =</span> <span class="fu">case_when</span>(</span>
<span id="cb22-23"><a href="#cb22-23" tabindex="-1"></a>      TotalSteps <span class="sc">&lt;</span> <span class="dv">5000</span> <span class="sc">~</span> <span class="st">&quot;Low&quot;</span>,</span>
<span id="cb22-24"><a href="#cb22-24" tabindex="-1"></a>      TotalSteps <span class="sc">&gt;=</span> <span class="dv">5000</span> <span class="sc">&amp;</span> TotalSteps <span class="sc">&lt;</span> <span class="dv">10000</span> <span class="sc">~</span> <span class="st">&quot;Medium&quot;</span>,</span>
<span id="cb22-25"><a href="#cb22-25" tabindex="-1"></a>      TotalSteps <span class="sc">&gt;=</span> <span class="dv">10000</span> <span class="sc">~</span> <span class="st">&quot;High&quot;</span></span>
<span id="cb22-26"><a href="#cb22-26" tabindex="-1"></a>    )</span>
<span id="cb22-27"><a href="#cb22-27" tabindex="-1"></a>  )</span>
<span id="cb22-28"><a href="#cb22-28" tabindex="-1"></a></span>
<span id="cb22-29"><a href="#cb22-29" tabindex="-1"></a><span class="co"># Fix weight log dates</span></span>
<span id="cb22-30"><a href="#cb22-30" tabindex="-1"></a>weight_log_info <span class="ot">&lt;-</span> weight_log_info <span class="sc">%&gt;%</span></span>
<span id="cb22-31"><a href="#cb22-31" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">mdy_hms</span>(Date))</span>
<span id="cb22-32"><a href="#cb22-32" tabindex="-1"></a></span>
<span id="cb22-33"><a href="#cb22-33" tabindex="-1"></a><span class="co"># Remove WeightPounds (we’ll keep kg version)</span></span>
<span id="cb22-34"><a href="#cb22-34" tabindex="-1"></a>weight_log_info <span class="ot">&lt;-</span> weight_log_info <span class="sc">%&gt;%</span></span>
<span id="cb22-35"><a href="#cb22-35" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>WeightPounds)</span>
<span id="cb22-36"><a href="#cb22-36" tabindex="-1"></a></span>
<span id="cb22-37"><a href="#cb22-37" tabindex="-1"></a>weight_cleaned <span class="ot">&lt;-</span> weight_log_info <span class="sc">%&gt;%</span></span>
<span id="cb22-38"><a href="#cb22-38" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-39"><a href="#cb22-39" tabindex="-1"></a>    <span class="at">DateTime =</span> <span class="fu">as.POSIXct</span>(Date, <span class="at">format =</span> <span class="st">&quot;%m/%d/%Y %I:%M:%S %p&quot;</span>),</span>
<span id="cb22-40"><a href="#cb22-40" tabindex="-1"></a>    <span class="at">Date =</span> <span class="fu">as.Date</span>(DateTime),</span>
<span id="cb22-41"><a href="#cb22-41" tabindex="-1"></a>    <span class="at">Time =</span> <span class="fu">format</span>(DateTime, <span class="st">&quot;%H:%M:%S&quot;</span>)</span>
<span id="cb22-42"><a href="#cb22-42" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb22-43"><a href="#cb22-43" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Time =</span> <span class="fu">as_hms</span>(Time))</span>
<span id="cb22-44"><a href="#cb22-44" tabindex="-1"></a></span>
<span id="cb22-45"><a href="#cb22-45" tabindex="-1"></a><span class="co"># Fix datetime in the hourly steps dataset</span></span>
<span id="cb22-46"><a href="#cb22-46" tabindex="-1"></a></span>
<span id="cb22-47"><a href="#cb22-47" tabindex="-1"></a>hourly_steps <span class="ot">&lt;-</span> hourly_steps <span class="sc">%&gt;%</span></span>
<span id="cb22-48"><a href="#cb22-48" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ActivityHour =</span> <span class="fu">mdy_hms</span>(ActivityHour))</span>
<span id="cb22-49"><a href="#cb22-49" tabindex="-1"></a></span>
<span id="cb22-50"><a href="#cb22-50" tabindex="-1"></a><span class="co"># Remove duplicates</span></span>
<span id="cb22-51"><a href="#cb22-51" tabindex="-1"></a>daily_activity_clean <span class="ot">&lt;-</span> daily_activity <span class="sc">%&gt;%</span></span>
<span id="cb22-52"><a href="#cb22-52" tabindex="-1"></a>  <span class="fu">distinct</span>(Id, ActivityDate, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-53"><a href="#cb22-53" tabindex="-1"></a></span>
<span id="cb22-54"><a href="#cb22-54" tabindex="-1"></a>sleep_clean <span class="ot">&lt;-</span> sleep_day <span class="sc">%&gt;%</span></span>
<span id="cb22-55"><a href="#cb22-55" tabindex="-1"></a>  <span class="fu">distinct</span>(Id, SleepDay, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-56"><a href="#cb22-56" tabindex="-1"></a></span>
<span id="cb22-57"><a href="#cb22-57" tabindex="-1"></a>weight_clean <span class="ot">&lt;-</span> weight_cleaned <span class="sc">%&gt;%</span></span>
<span id="cb22-58"><a href="#cb22-58" tabindex="-1"></a>  <span class="fu">distinct</span>(Id, Date, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-59"><a href="#cb22-59" tabindex="-1"></a></span>
<span id="cb22-60"><a href="#cb22-60" tabindex="-1"></a>hourly_steps_clean <span class="ot">&lt;-</span> hourly_steps <span class="sc">%&gt;%</span></span>
<span id="cb22-61"><a href="#cb22-61" tabindex="-1"></a>  <span class="fu">distinct</span>(Id, ActivityHour, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-62"><a href="#cb22-62" tabindex="-1"></a></span>
<span id="cb22-63"><a href="#cb22-63" tabindex="-1"></a><span class="co"># Add Day Type</span></span>
<span id="cb22-64"><a href="#cb22-64" tabindex="-1"></a>daily_activity_clean <span class="ot">&lt;-</span> daily_activity_clean <span class="sc">%&gt;%</span></span>
<span id="cb22-65"><a href="#cb22-65" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-66"><a href="#cb22-66" tabindex="-1"></a>    <span class="at">DayType =</span> <span class="fu">if_else</span>(<span class="fu">weekdays</span>(ActivityDate) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Saturday&quot;</span>, <span class="st">&quot;Sunday&quot;</span>),</span>
<span id="cb22-67"><a href="#cb22-67" tabindex="-1"></a>                       <span class="st">&quot;Weekend&quot;</span>, <span class="st">&quot;Weekday&quot;</span>)</span>
<span id="cb22-68"><a href="#cb22-68" tabindex="-1"></a>  )</span>
<span id="cb22-69"><a href="#cb22-69" tabindex="-1"></a></span>
<span id="cb22-70"><a href="#cb22-70" tabindex="-1"></a>sleep_clean <span class="ot">&lt;-</span> sleep_clean <span class="sc">%&gt;%</span></span>
<span id="cb22-71"><a href="#cb22-71" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-72"><a href="#cb22-72" tabindex="-1"></a>    <span class="at">DayType =</span> <span class="fu">ifelse</span>(<span class="fu">wday</span>(SleepDay) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">7</span>), <span class="st">&quot;Weekend&quot;</span>, <span class="st">&quot;Weekday&quot;</span>)</span>
<span id="cb22-73"><a href="#cb22-73" tabindex="-1"></a>  )</span>
<span id="cb22-74"><a href="#cb22-74" tabindex="-1"></a></span>
<span id="cb22-75"><a href="#cb22-75" tabindex="-1"></a>hourly_steps_clean <span class="ot">&lt;-</span> hourly_steps_clean <span class="sc">%&gt;%</span></span>
<span id="cb22-76"><a href="#cb22-76" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-77"><a href="#cb22-77" tabindex="-1"></a>    <span class="at">DayType =</span> <span class="fu">ifelse</span>(<span class="fu">wday</span>(ActivityHour) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">7</span>), <span class="st">&quot;Weekend&quot;</span>, <span class="st">&quot;Weekday&quot;</span>)</span>
<span id="cb22-78"><a href="#cb22-78" tabindex="-1"></a>  )</span>
<span id="cb22-79"><a href="#cb22-79" tabindex="-1"></a><span class="co"># Standarizing column names using janitor</span></span>
<span id="cb22-80"><a href="#cb22-80" tabindex="-1"></a></span>
<span id="cb22-81"><a href="#cb22-81" tabindex="-1"></a>daily_activity_clean <span class="ot">&lt;-</span>daily_activity_clean <span class="sc">%&gt;%</span></span>
<span id="cb22-82"><a href="#cb22-82" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span>
<span id="cb22-83"><a href="#cb22-83" tabindex="-1"></a></span>
<span id="cb22-84"><a href="#cb22-84" tabindex="-1"></a>sleep_clean <span class="ot">&lt;-</span> sleep_clean <span class="sc">%&gt;%</span></span>
<span id="cb22-85"><a href="#cb22-85" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span>
<span id="cb22-86"><a href="#cb22-86" tabindex="-1"></a></span>
<span id="cb22-87"><a href="#cb22-87" tabindex="-1"></a>weight_clean <span class="ot">&lt;-</span> weight_clean <span class="sc">%&gt;%</span></span>
<span id="cb22-88"><a href="#cb22-88" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span>
<span id="cb22-89"><a href="#cb22-89" tabindex="-1"></a></span>
<span id="cb22-90"><a href="#cb22-90" tabindex="-1"></a>hourly_steps_clean <span class="ot">&lt;-</span> hourly_steps_clean <span class="sc">%&gt;%</span></span>
<span id="cb22-91"><a href="#cb22-91" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span></code></pre></div>
</div>
<div id="responsibilities-and-key-actions" class="section level4">
<h4>Responsibilities and Key Actions</h4>
<ul>
<li>Imported and consolidated datasets from March–April and
April–May.<br />
</li>
<li>Applied <code>janitor::clean_names()</code> across all datasets to
ensure consistent, clear, and standardized column names.<br />
</li>
<li>Ensured datasets were properly formatted and ready for
analysis.</li>
</ul>
</div>
<div id="data-cleaning-and-standardization" class="section level4">
<h4>Data Cleaning and Standardization</h4>
<ul>
<li>Converted date and datetime fields (<strong>activity_date,
sleep_day, activity_hour, date</strong>) into proper R formats.<br />
</li>
<li>Removed duplicate records across datasets to maintain
integrity.</li>
</ul>
<div id="new-variables" class="section level5">
<h5>New Variables</h5>
<ul>
<li><strong>weight_kg</strong> retained; <strong>weight_pounds</strong>
removed
<ul>
<li>Why: Kilograms are consistent and internationally standard.<br />
</li>
</ul></li>
<li><strong>sleep_efficiency</strong> =
<code>total_minutes_asleep / total_time_in_bed * 100</code>
<ul>
<li>Why: Provides a standardized measure of sleep quality.<br />
</li>
</ul></li>
<li><strong>day_type</strong> classified as <em>weekday</em> or
<em>weekend</em>
<ul>
<li>Why: Captures behavioral differences across day types.<br />
</li>
</ul></li>
<li><strong>activity_level</strong> categorized as <em>low</em>,
<em>medium</em>, <em>high</em> based on daily steps
<ul>
<li>Why: Easier to summarize and communicate activity trends.</li>
</ul></li>
</ul>
</div>
</div>
<div id="dataset-merging" class="section level4">
<h4>Dataset Merging</h4>
<ul>
<li>Unified datasets across both periods for:<br />
<em>daily_activity, sleep_day, weight_log_info, hourly_steps</em></li>
</ul>
</div>
<div id="data-validation-and-integrity" class="section level4">
<h4>Data Validation and Integrity</h4>
<ul>
<li>Counted duplicates per user/date/hour.<br />
</li>
<li>Summarized daily and weekly measures to detect
inconsistencies.<br />
</li>
<li>Built reproducible workflow for future updates.</li>
</ul>
</div>
<div id="achievements-and-deliverables" class="section level4">
<h4>Achievements and Deliverables</h4>
<ul>
<li>4 fully cleaned datasets ready for analysis.<br />
</li>
<li>Removed duplicates and inconsistencies → ensured higher data
quality.<br />
</li>
<li>Standardized datetime and categorical variables.<br />
</li>
<li>Created <strong>intermediate variables</strong> (<em>activity_level,
sleep_efficiency, day_type</em>) for deeper insights.</li>
</ul>
</div>
<div id="cleaned-datasets-ready-for-analysis" class="section level4">
<h4>Cleaned Datasets Ready for Analysis</h4>
<ul>
<li><code>daily_activity_clean</code><br />
</li>
<li><code>sleep_clean</code><br />
</li>
<li><code>weight_clean</code><br />
</li>
<li><code>hourly_steps_clean</code></li>
</ul>
</div>
</div>
<div id="analyze-and-share" class="section level2">
<h2>🔎 Analyze and 📢 Share</h2>
<div id="distribution-of-daily-steps-across-all-users"
class="section level3">
<h3>Distribution of Daily Steps across All Users</h3>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">ggplot</span>(daily_activity_clean, <span class="fu">aes</span>(<span class="at">x=</span>total_steps))<span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span> <span class="dv">2000</span>, <span class="at">fill=</span><span class="st">&quot;skyblue&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>)<span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a>    <span class="at">title=</span><span class="st">&quot;Distribution of Daily Steps&quot;</span>,</span>
<span id="cb23-5"><a href="#cb23-5" tabindex="-1"></a>    <span class="at">x=</span><span class="st">&quot;Total steps per user&quot;</span>,</span>
<span id="cb23-6"><a href="#cb23-6" tabindex="-1"></a>    <span class="at">y=</span><span class="st">&quot;Number of days&quot;</span>)<span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div id="finding-data-insight" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>Most days users record between 0 and 12,000 steps, peaking around
10,000.</li>
<li>Very few days exceed 20,000 steps.</li>
</ul>
</div>
<div id="interpretation-user-behavior" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Users’ activity aligns with the common 10,000-step health goal.</li>
<li>However, many days fall under 5,000 steps → sedentary or inactive
users.</li>
</ul>
</div>
<div id="business-implication-bellabeat" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li><p>Segmented Marketing and Messaging: Bellabeat should use a dual
marketing approach. For the active users, messaging should highlight
advanced features and performance optimization. For the less active, the
focus should be on motivation, encouragement, and the benefits of small,
achievable goals.</p></li>
<li><p>Targeted Product Features: Develop distinct features for each
user group. For highly active users, introduce advanced analytics and
workout logging. For less active users, implement gamified challenges
and a “step-up” program that rewards gradual increases in activity to
build lasting habits.</p></li>
<li><p>Strategic Content: Tailor content to user needs. Provide training
tips and performance insights for the active segment, while offering
simple tips and motivational stories for those who are more sedentary.
This builds stronger engagement and brand loyalty across the entire
customer base.</p></li>
</ul>
</div>
</div>
<div id="boxplots-by-day-type-for-steps" class="section level3">
<h3>Boxplots by day type for steps</h3>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="fu">ggplot</span>(daily_activity_clean, <span class="fu">aes</span>(<span class="at">x =</span> day_type, <span class="at">y =</span> total_steps, <span class="at">fill =</span> day_type)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Steps: Weekday vs Weekend&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Day Type&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Total Steps&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Weekday&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>, <span class="st">&quot;Weekend&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightpink&quot;</span>)) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div id="finding-data-insight-1" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The boxplot shows that users generally walk up to 10,000 steps on
both weekdays and weekends.</li>
<li>Very few days exceed 20,000 steps.</li>
<li>The distribution is similar across weekdays and weekends.</li>
</ul>
</div>
<div id="interpretation-user-behavior-1" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Users’ walking habits remain consistent regardless of the day of the
week.</li>
<li>No major behavioral difference between weekdays and weekends.</li>
</ul>
</div>
<div id="business-implication-bellabeat-1" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can deliver activity nudges and motivational campaigns
uniformly across weekdays and weekends.</li>
<li>A unified approach saves resources and ensures consistent
engagement.</li>
</ul>
</div>
</div>
<div id="boxplots-by-day-type-for-calories" class="section level3">
<h3>Boxplots by day type for calories</h3>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="fu">ggplot</span>(daily_activity_clean, <span class="fu">aes</span>(<span class="at">x =</span> day_type, <span class="at">y =</span> calories, <span class="at">fill =</span> day_type)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Calories Burned: Weekday vs Weekend&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Day Type&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Calories&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Weekday&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>, <span class="st">&quot;Weekend&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightpink&quot;</span>)) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div id="finding-data-insight-2" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>Most users burn between 1,500 and 3,000 calories per day.</li>
<li>The median is around 2,200–2,300 calories.</li>
<li>The distribution is very similar on weekdays and weekends.</li>
</ul>
</div>
<div id="interpretation-user-behavior-2" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Users show consistent calorie expenditure across the entire
week.</li>
<li>No significant variation between weekdays and weekends.</li>
</ul>
</div>
<div id="business-implication-bellabeat-2" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can offer unified nutrition and activity plans without
needing weekday/weekend differentiation.</li>
<li>Simplified recommendations increase user adherence and reduce
complexity in product design.</li>
</ul>
</div>
</div>
<div id="steps-vs-calories-scatter-outliers" class="section level3">
<h3>Steps vs calories scatter + outliers</h3>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> daily_activity_clean <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>  <span class="fu">filter</span>(total_steps <span class="sc">&lt;</span> <span class="dv">2000</span> <span class="sc">|</span> total_steps <span class="sc">&gt;</span> <span class="dv">20000</span>)</span>
<span id="cb26-3"><a href="#cb26-3" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" tabindex="-1"></a><span class="fu">ggplot</span>(daily_activity_clean, <span class="fu">aes</span>(<span class="at">x =</span> total_steps, <span class="at">y =</span> calories)) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> outliers, <span class="fu">aes</span>(<span class="at">x =</span> total_steps, <span class="at">y =</span> calories, <span class="at">color =</span> activity_level), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Steps vs Calories Burned (Outliers Highlighted)&quot;</span>,</span>
<span id="cb26-8"><a href="#cb26-8" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Total Steps&quot;</span>,</span>
<span id="cb26-9"><a href="#cb26-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Calories Burned&quot;</span>,</span>
<span id="cb26-10"><a href="#cb26-10" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">&quot;Activity Level&quot;</span>) <span class="sc">+</span></span>
<span id="cb26-11"><a href="#cb26-11" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div id="finding-data-insight-3" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The scatterplot shows a direct correlation between total steps and
calories burned.</li>
<li>Most data points fall between ~2,000 and 15,000 steps, corresponding
to ~1,500–3,000 calories burned.</li>
<li>Outliers (highlighted in blue and red) confirm the overall
trend.</li>
</ul>
</div>
<div id="interpretation-user-behavior-3" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Higher step counts are generally associated with higher calorie
expenditure.</li>
<li>Active users (5,000–10,000 steps/day) tend to maintain calorie burn
within the healthy range of ~2,000–3,000.</li>
<li>While 10,000 steps alone does not guarantee 2,000 calories burned,
it strongly contributes to consistent energy expenditure.</li>
</ul>
</div>
<div id="business-implication-bellabeat-3" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can encourage users to aim for 5,000–10,000 steps per day
as a sustainable and healthy activity habit.</li>
<li>Positioning this as an achievable daily goal can drive user
motivation and long-term adherence.</li>
</ul>
</div>
</div>
<div id="average-steps-over-time" class="section level3">
<h3>Average steps over time</h3>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a>daily_activity_clean <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a>  <span class="fu">group_by</span>(activity_date) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_steps =</span> <span class="fu">mean</span>(total_steps)) <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> activity_date, <span class="at">y =</span> avg_steps)) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Average Steps Over Time&quot;</span>,</span>
<span id="cb27-7"><a href="#cb27-7" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average Steps&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div id="finding-data-insight-4" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The line chart shows that average daily steps fluctuate early in the
period but stabilize in April and May.</li>
<li>From mid-April onward, users consistently reach ~7,000–8,000 steps
per day.</li>
<li>Early March shows irregular activity with several low-step
days.</li>
</ul>
</div>
<div id="interpretation-user-behavior-4" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Users demonstrate progressive improvement in activity levels over
time, suggesting adaptation or motivation to maintain higher step
counts.</li>
<li>The stabilization near 7,000–8,000 steps indicates a sustainable
average for many users.</li>
<li>Periodic drops suggest challenges in maintaining consistency (e.g.,
weekends, personal factors).</li>
</ul>
</div>
<div id="business-implication-bellabeat-4" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can highlight progress trends in the app to reinforce
positive behavior and celebrate milestones.</li>
<li>Providing personalized streak challenges (e.g., maintaining 7,000+
steps for a week) can help users stay consistent.</li>
<li>By addressing dips with nudges or reminders, Bellabeat can improve
user adherence and engagement.</li>
</ul>
</div>
</div>
<div id="correlation-analysis-steps-vs.-calories"
class="section level3">
<h3>Correlation Analysis: Steps vs. Calories</h3>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="fu">cor</span>(daily_activity_clean<span class="sc">$</span>total_steps, daily_activity_clean<span class="sc">$</span>calories)</span></code></pre></div>
<pre><code>## [1] 0.5913044</code></pre>
<div id="finding-data-insight-5" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The correlation between steps and calories burned is moderate and
positive (r = 0.59).</li>
<li>More steps generally lead to higher calorie expenditure, but the
relationship is not perfect.</li>
<li>Variation across users suggests other influencing factors (e.g.,
intensity, duration, individual metabolism).</li>
</ul>
</div>
<div id="interpretation-user-behavior-5" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Users who walk more tend to burn more calories, but simply
increasing step count does not guarantee higher calorie burn.</li>
<li>Exercise intensity and activity type also play an important
role.</li>
</ul>
</div>
<div id="business-implication-bellabeat-5" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can educate users about the combined impact of step count,
intensity, and duration on calorie burn.</li>
<li>The app can deliver smarter nudges, encouraging users not only to
increase steps but also to include higher-intensity activities.</li>
<li>This holistic approach improves user awareness and supports
healthier outcomes</li>
</ul>
</div>
</div>
<div id="average-sleep-by-day-type" class="section level3">
<h3>Average Sleep by Day Type</h3>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a>sleep_clean <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" tabindex="-1"></a>  <span class="fu">group_by</span>(day_type) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb30-4"><a href="#cb30-4" tabindex="-1"></a>    <span class="at">avg_sleep_min =</span> <span class="fu">mean</span>(total_minutes_asleep, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-5"><a href="#cb30-5" tabindex="-1"></a>    <span class="at">median_sleep_min =</span> <span class="fu">median</span>(total_minutes_asleep, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-6"><a href="#cb30-6" tabindex="-1"></a>    <span class="at">avg_efficiency =</span> <span class="fu">mean</span>(sleep_efficiency, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-7"><a href="#cb30-7" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   day_type avg_sleep_min median_sleep_min avg_efficiency
##   &lt;chr&gt;            &lt;dbl&gt;            &lt;dbl&gt;          &lt;dbl&gt;
## 1 Weekday           413.             426            91.9
## 2 Weekend           436.             464.           91.0</code></pre>
<div id="finding-data-insight-6" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>On weekdays, users sleep ~6.9 hours (median 7.1) with 91.9%
efficiency.</li>
<li>On weekends, users sleep ~7.3–7.7 hours with slightly lower
efficiency (91.0%).</li>
</ul>
</div>
<div id="interpretation-user-behavior-6" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Users tend to sleep less during weekdays and compensate on weekends
(sleep debt pattern).</li>
<li>Longer sleep on weekends does not improve quality, possibly due to
irregular schedules.</li>
</ul>
</div>
<div id="business-implication-bellabeat-6" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can promote consistent sleep routines (“consistency over
quantity”).</li>
<li>The app could offer sleep debt alerts and classify users at risk of
irregular sleep patterns, encouraging healthier habits.</li>
</ul>
</div>
</div>
<div id="histogram-of-total-sleep" class="section level3">
<h3>Histogram of total sleep</h3>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="fu">ggplot</span>(sleep_clean, <span class="fu">aes</span>(<span class="at">x =</span> total_minutes_asleep)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of Total Sleep Minutes&quot;</span>,</span>
<span id="cb32-4"><a href="#cb32-4" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Minutes Asleep&quot;</span>,</span>
<span id="cb32-5"><a href="#cb32-5" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Number of Nights&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<div id="finding-data-insight-7" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The majority of nights fall between 350 and 500 minutes of sleep (≈
6–8 hours).</li>
<li>The peak is around 420–450 minutes (~7 hours). There are some
outliers: very short sleep (&lt;200 minutes) and very long sleep
(&gt;700 minutes).</li>
</ul>
</div>
<div id="interpretation-user-behavior-7" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Most users meet the general recommendation of ~7 hours of
sleep.</li>
<li>A notable group sleeps significantly less (&lt;5 hours), indicating
sleep deprivation risk.</li>
<li>A smaller group oversleeps (&gt;10 hours), which may reflect
irregular sleep patterns or health-related issues.</li>
</ul>
</div>
<div id="business-implication-bellabeat-7" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can reinforce healthy sleepers (~7 hours) with
motivational feedback.</li>
<li>Target users with &lt;5 hours using alerts and educational nudges
about sleep health.</li>
<li>The app could flag irregular patterns (too little or too much sleep)
and suggest actionable routines to improve sleep consistency</li>
</ul>
</div>
</div>
<div id="boxplot-sleep-by-day-type" class="section level3">
<h3>Boxplot sleep by day type</h3>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a><span class="fu">ggplot</span>(sleep_clean, <span class="fu">aes</span>(<span class="at">x =</span> day_type, <span class="at">y =</span> total_minutes_asleep, <span class="at">fill =</span> day_type)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Sleep Duration: Weekday vs Weekend&quot;</span>,</span>
<span id="cb33-4"><a href="#cb33-4" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Day Type&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Minutes Asleep&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Weekday&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>, <span class="st">&quot;Weekend&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightpink&quot;</span>)) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<div id="finding-data-insight-8" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>On weekends, median sleep duration rises to 7.5–8 hours (450–480
min).</li>
<li>On weekdays, median sleep remains lower at around 7 hours (420
min).</li>
<li>This indicates a shift in sleep duration depending on the day
type.</li>
</ul>
</div>
<div id="interpretation-user-behavior-8" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Users sleep less during weekdays, likely due to work or study
schedules.</li>
<li>On weekends, they compensate by sleeping longer, a common “sleep
debt” pattern.</li>
<li>This suggests that weekday routines negatively impact consistent
rest.</li>
</ul>
</div>
<div id="business-implication-bellabeat-8" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can promote regular sleep schedules, emphasizing that
weekend compensation does not replace daily quality rest.</li>
<li>The app could provide smart reminders on weekdays to encourage
earlier bedtimes.</li>
<li>Sleep hygiene programs can be targeted at users with large
weekday–weekend gaps to reduce long-term sleep debt.</li>
</ul>
</div>
</div>
<div id="outliers" class="section level3">
<h3>Outliers</h3>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a>sleep_outliers <span class="ot">&lt;-</span> sleep_clean <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>  <span class="fu">filter</span>(total_minutes_asleep <span class="sc">&lt;</span> <span class="dv">300</span> <span class="sc">|</span> total_minutes_asleep <span class="sc">&gt;</span> <span class="dv">900</span>)</span>
<span id="cb34-3"><a href="#cb34-3" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> sleep_clean,</span>
<span id="cb34-6"><a href="#cb34-6" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> total_minutes_asleep, <span class="at">y =</span> sleep_efficiency, <span class="at">color =</span> <span class="st">&quot;Normal&quot;</span>),</span>
<span id="cb34-7"><a href="#cb34-7" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> sleep_outliers,</span>
<span id="cb34-9"><a href="#cb34-9" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> total_minutes_asleep, <span class="at">y =</span> sleep_efficiency, <span class="at">color =</span> <span class="st">&quot;Outlier&quot;</span>),</span>
<span id="cb34-10"><a href="#cb34-10" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb34-11"><a href="#cb34-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Sleep Minutes vs Efficiency (Outliers Highlighted)&quot;</span>,</span>
<span id="cb34-12"><a href="#cb34-12" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Minutes Asleep&quot;</span>,</span>
<span id="cb34-13"><a href="#cb34-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Sleep Efficiency&quot;</span>,</span>
<span id="cb34-14"><a href="#cb34-14" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">&quot;Sleep Category&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-15"><a href="#cb34-15" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Normal&quot;</span> <span class="ot">=</span> <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;Outlier&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>)) <span class="sc">+</span></span>
<span id="cb34-16"><a href="#cb34-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div id="finding-data-insight-9" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>Most users (blue points) cluster around 350–500 minutes of sleep
with efficiency &gt;85%.</li>
<li>Outliers (red points) show very short sleep (&lt;200 minutes) or
unusually low efficiency (&lt;70%).</li>
<li>A few cases show long sleep durations (&gt;600 minutes) but not
necessarily higher efficiency.</li>
</ul>
</div>
<div id="interpretation-user-behavior-9" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Normal sleepers maintain both adequate duration and good efficiency,
aligning with healthy sleep patterns.</li>
<li>Outliers indicate sleep irregularities: some users sleep too little,
or their sleep is fragmented/inefficient.</li>
<li>Longer sleep does not always equal better quality, suggesting
inconsistency in rest routines.</li>
</ul>
</div>
<div id="business-implication-bellabeat-9" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can flag users with abnormal sleep patterns (too short,
too long, or low efficiency) and provide tailored recommendations.</li>
<li>Promote sleep quality education, emphasizing efficiency and
consistency over just duration.</li>
<li>Use personalized interventions (alerts, routines, or sleep hygiene
programs) to reduce inefficiency and support healthier rest habits.</li>
</ul>
</div>
</div>
<div id="average-steps-per-hour" class="section level3">
<h3>Average steps per hour</h3>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a>hourly_steps_clean <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hour =</span> <span class="fu">hour</span>(activity_hour)) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" tabindex="-1"></a>  <span class="fu">group_by</span>(hour) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_steps =</span> <span class="fu">mean</span>(step_total)) <span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> hour, <span class="at">y =</span> avg_steps)) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Average Steps by Hour&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Hour of Day&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average Steps&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div id="finding-data-insight-10" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The line graph shows the average number of steps taken for each hour
of the day.</li>
<li>There is very low activity from midnight until around 5 a.m.</li>
<li>Activity increases sharply in the morning, peaking around 9
a.m.</li>
<li>A second, more pronounced peak occurs in the evening, from
approximately 5 p.m. to 8 p.m., before activity drops off again.</li>
</ul>
</div>
<div id="interpretation-user-behavior-10" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>The two distinct peaks correspond to common daily routines, likely a
morning commute or workout, and an evening workout or after-work
activity.</li>
<li>The low activity during the night and the dip in the afternoon
(around 1 p.m. to 3 p.m.) suggest periods of rest or sedentary behavior,
such as work hours or lunch.</li>
<li>The overall pattern shows that users are more active during the
evening hours.</li>
</ul>
</div>
<div id="business-implication-bellabeat-10" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can capitalize on the two main activity windows by
scheduling targeted in-app notifications and challenges to encourage
activity. For example, a reminder at 4 p.m. to “prepare for your evening
workout.”</li>
<li>The company can promote its products as tools for tracking steps
during the day and for rewarding progress during the evening peak.</li>
<li>Bellabeat could also introduce features that encourage movement
during the midday dip to help users combat sedentary habits.</li>
</ul>
</div>
</div>
<div id="compare-weekday-vs-weekend-steps-by-hour"
class="section level3">
<h3>Compare weekday vs weekend steps by hour</h3>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a>hourly_steps_clean <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hour =</span> <span class="fu">hour</span>(activity_hour)) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" tabindex="-1"></a>  <span class="fu">group_by</span>(day_type, hour) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_steps =</span> <span class="fu">mean</span>(step_total)) <span class="sc">%&gt;%</span></span>
<span id="cb36-5"><a href="#cb36-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> hour, <span class="at">y =</span> avg_steps, <span class="at">color =</span> day_type)) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Hourly Steps: Weekday vs Weekend&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Hour of Day&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average Steps&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;day_type&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<div id="finding-data-insight-11" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The graph shows the average hours of sleep per day of the week, for
both weekdays and weekends.</li>
<li>The blue line represents the average sleep on weekends, and the red
line represents the average sleep on weekdays.</li>
<li>On weekdays, the average sleep duration is consistently lower,
hovering around 6.5 to 7 hours.</li>
<li>On weekends, the average sleep duration is significantly higher,
consistently above 7.5 hours.</li>
<li>Both lines show a “U” shape, with sleep hours being highest on
Monday/Tuesday and Friday/Saturday and lowest in the middle of the
week.</li>
</ul>
</div>
<div id="interpretation-user-behavior-11" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>The lower average sleep during weekdays suggests that users may be
experiencing “sleep debt,” where they get less sleep than needed during
the week and try to “catch up” on the weekends.</li>
<li>The graph indicates a clear and predictable weekly pattern in user
behavior. Users prioritize work/other activities over sleep during the
week but dedicate more time to rest on weekends.</li>
</ul>
</div>
<div id="business-implication-bellabeat-11" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat’s marketing and app features should address the issue of
sleep debt directly. For example, Bellabeat can send a gentle “sleep
reminder” notification on weekday evenings to encourage users to go to
bed earlier.</li>
<li>The app could offer content or features that educate users on the
importance of consistent sleep schedules and how sleep debt can affect
overall health and well-being.</li>
<li>The company could promote its products as tools for monitoring and
improving sleep quality, especially during the week when users are most
deficient. This could include personalized sleep recommendations based
on daily activity and stress levels.</li>
</ul>
</div>
</div>
<div id="heatmap-steps-by-hour-and-day-type" class="section level3">
<h3>Heatmap steps by hour and day type</h3>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" tabindex="-1"></a>hourly_steps_clean <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hour =</span> <span class="fu">hour</span>(activity_hour)) <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" tabindex="-1"></a>  <span class="fu">group_by</span>(day_type, hour) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_steps =</span> <span class="fu">mean</span>(step_total)) <span class="sc">%&gt;%</span></span>
<span id="cb39-5"><a href="#cb39-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> hour, <span class="at">y =</span> day_type, <span class="at">fill =</span> avg_steps)) <span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Heatmap: Average Hourly Steps by Day Type&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Hour&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Day Type&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;Avg Steps&quot;</span>) <span class="sc">+</span></span>
<span id="cb39-9"><a href="#cb39-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;day_type&#39;. You can override using the
## `.groups` argument.</code></pre>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<div id="finding-data-insight-12" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The heatmap shows that users’ step counts peak in the morning and
evening on both weekdays and weekends.</li>
<li>Weekday morning activity peaks between 7 am and 9 am, while the
evening peak is from 5 pm to 7 pm.</li>
<li>On weekends, the morning peak starts later, around 9 am, and the
evening peak is broader and more intense, lasting from 5 pm to 9
pm.</li>
</ul>
</div>
<div id="interpretation-user-behavior-12" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>The weekday peaks likely correspond to commutes and post-work
exercise routines.</li>
<li>The later, more intense weekend activity suggests that users have
more free time and engage in more extended activities.</li>
</ul>
</div>
<div id="business-implication-bellabeat-12" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can send targeted notifications and challenges during the
peak activity hours (e.g., 4 pm on weekdays) to encourage pre-exercise
preparation.</li>
<li>The app could introduce a “Weekend Challenge” that aligns with the
later morning start and longer evening activity periods to maximize user
engagement.</li>
<li>Bellabeat can also offer “micro-challenges” during the typically
inactive daytime hours to help users with sedentary jobs increase their
daily steps</li>
</ul>
</div>
</div>
<div id="average-weight-bmi-profile-of-user" class="section level3">
<h3>Average Weight &amp; BMI Profile of User</h3>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" tabindex="-1"></a>weight_clean <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb41-3"><a href="#cb41-3" tabindex="-1"></a>    <span class="at">avg_weight =</span> <span class="fu">mean</span>(weight_kg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-4"><a href="#cb41-4" tabindex="-1"></a>    <span class="at">avg_BMI =</span> <span class="fu">mean</span>(bmi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-5"><a href="#cb41-5" tabindex="-1"></a>    <span class="at">avg_fat =</span> <span class="fu">mean</span>(fat, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb41-6"><a href="#cb41-6" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   avg_weight avg_BMI avg_fat
##        &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1       72.5    25.4    19.8</code></pre>
<div id="finding-data-insight-13" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The average weight of users is 72.5 kg.</li>
<li>The average BMI is 25.4, which falls in the overweight range
(≥25).</li>
<li>The average body fat percentage is 19.8%, within a generally healthy
range but needing context by gender and lifestyle.</li>
</ul>
</div>
<div id="interpretation-user-behavior-13" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Many users are close to or slightly above the healthy BMI threshold,
suggesting that weight management is a concern.</li>
<li>The relatively moderate body fat percentage may indicate that not
all excess BMI is due to unhealthy fat mass—it could be lifestyle
factors (diet, sedentary behavior, lack of activity).</li>
<li>Users may not be fully aligning dietary habits with physical
activity, leading to BMI creeping into the overweight range.</li>
</ul>
</div>
<div id="business-implication-bellabeat-13" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can develop personalized weight management programs,
linking activity tracking with nutrition and lifestyle insights.</li>
<li>Introduce BMI and body composition trackers with progress alerts,
helping users stay in or return to the healthy range.</li>
<li>Provide educational content on the difference between weight, BMI,
and fat %, helping users interpret their numbers correctly.</li>
<li>Launch gamified challenges (e.g., step goals, hydration, mindful
eating streaks) that support maintaining a healthy balance.</li>
</ul>
</div>
</div>
<div id="user-level-weight-trends-top-5-weight-losers-and-top-5-gainers"
class="section level3">
<h3>User-level weight trends (Top 5 weight losers and top 5
gainers)</h3>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" tabindex="-1"></a>user_weight_trends <span class="ot">&lt;-</span> weight_clean <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" tabindex="-1"></a>  <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb43-4"><a href="#cb43-4" tabindex="-1"></a>    <span class="at">start_weight =</span> <span class="fu">first</span>(weight_kg),</span>
<span id="cb43-5"><a href="#cb43-5" tabindex="-1"></a>    <span class="at">end_weight =</span> <span class="fu">last</span>(weight_kg),</span>
<span id="cb43-6"><a href="#cb43-6" tabindex="-1"></a>    <span class="at">weight_change =</span> <span class="fu">last</span>(weight_kg) <span class="sc">-</span> <span class="fu">first</span>(weight_kg),</span>
<span id="cb43-7"><a href="#cb43-7" tabindex="-1"></a>    <span class="at">start_BMI =</span> <span class="fu">first</span>(bmi),</span>
<span id="cb43-8"><a href="#cb43-8" tabindex="-1"></a>    <span class="at">end_BMI =</span> <span class="fu">last</span>(bmi),</span>
<span id="cb43-9"><a href="#cb43-9" tabindex="-1"></a>    <span class="at">BMI_change =</span> <span class="fu">last</span>(bmi) <span class="sc">-</span> <span class="fu">first</span>(bmi)</span>
<span id="cb43-10"><a href="#cb43-10" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb43-11"><a href="#cb43-11" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(weight_change))</span>
<span id="cb43-12"><a href="#cb43-12" tabindex="-1"></a></span>
<span id="cb43-13"><a href="#cb43-13" tabindex="-1"></a>top_losers <span class="ot">&lt;-</span> user_weight_trends <span class="sc">%&gt;%</span> <span class="fu">filter</span>(weight_change <span class="sc">&lt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">slice_min</span>(weight_change, <span class="at">n =</span> <span class="dv">5</span>)</span>
<span id="cb43-14"><a href="#cb43-14" tabindex="-1"></a>top_gainers <span class="ot">&lt;-</span> user_weight_trends <span class="sc">%&gt;%</span> <span class="fu">filter</span>(weight_change <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(weight_change, <span class="at">n =</span> <span class="dv">5</span>)</span>
<span id="cb43-15"><a href="#cb43-15" tabindex="-1"></a></span>
<span id="cb43-16"><a href="#cb43-16" tabindex="-1"></a>top_losers</span></code></pre></div>
<pre><code>## # A tibble: 4 × 7
##           id start_weight end_weight weight_change start_BMI end_BMI BMI_change
##        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
## 1 8877689391         85.5       84         -1.5         25.6    25.1    -0.470 
## 2 1503960366         53.3       52.6       -0.700       23.0    22.6    -0.320 
## 3 4558609924         69.4       69.1       -0.300       27.1    27      -0.140 
## 4 4319703577         72.4       72.3       -0.1000      27.5    27.4    -0.0700</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" tabindex="-1"></a>top_gainers</span></code></pre></div>
<pre><code>## # A tibble: 3 × 7
##           id start_weight end_weight weight_change start_BMI end_BMI BMI_change
##        &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
## 1 1927972279        130.       134.          3.90       46.2    47.5      1.37 
## 2 2873212765         56.7       57.3         0.600      21.5    21.7      0.240
## 3 6962181067         61.5       61.9         0.400      24.0    24.2      0.140</code></pre>
<div id="finding-data-insight-14" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The top weight losers reduced their weight by up to 1.5 kg over the
recorded period.</li>
<li>The top weight gainers increased their weight by up to 3.9 kg, with
smaller gains around 0.4–0.6 kg.</li>
<li>BMI changes mirror the weight trends, with maximum BMI decrease of
-0.47 and maximum increase of 1.37.</li>
</ul>
</div>
<div id="interpretation-user-behavior-14" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>Some users are successfully losing small amounts of weight,
suggesting positive engagement with activity or lifestyle tracking, but
the magnitude is limited.</li>
<li>Other users are gaining weight, including one substantial gain (3.9
kg), suggesting inconsistent adherence to healthy habits or lifestyle
changes that may counteract activity tracking.</li>
<li>Overall, users show heterogeneous behavior: a mix of modest progress
and weight gain, indicating that motivation and guidance may vary
widely.</li>
</ul>
</div>
<div id="business-implication-bellabeat-14" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can target users differently:
<ul>
<li>For users showing weight gain, provide proactive nudges and
personalized recommendations to improve activity and dietary
habits.</li>
<li>For users showing small losses, offer reinforcement and gamified
challenges to accelerate progress and maintain engagement.</li>
</ul></li>
<li>Introduce progress tracking dashboards that highlight weight trends,
BMI changes, and goals over time, helping users visualize results and
stay motivated.</li>
</ul>
</div>
</div>
<div id="weight-distributions-across-all-users" class="section level3">
<h3>Weight Distributions across All Users</h3>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="fu">ggplot</span>(weight_clean, <span class="fu">aes</span>(<span class="at">x =</span> weight_kg)) <span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill=</span><span class="st">&quot;skyblue&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;Weight Distribution of Users&quot;</span>, <span class="at">x=</span><span class="st">&quot;Weight (kg)&quot;</span>, <span class="at">y=</span><span class="st">&quot;Number of Records&quot;</span>) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<div id="finding-data-insight-15" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The histogram displays the distribution of user weights in
kilograms.</li>
<li>The distribution is bimodal, meaning it has two distinct peaks.</li>
<li>The first, smaller peak is located around 50 kg to 60 kg.</li>
<li>The second, larger peak is located around 75 kg to 85 kg.</li>
<li>There are no data points below 40 kg or above 90 kg.</li>
</ul>
</div>
<div id="interpretation-user-behavior-15" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>The bimodal distribution suggests the dataset contains two distinct
groups or populations of users.</li>
<li>It’s highly probable that these two groups correspond to two
different body types, perhaps related to gender. For example, one peak
could represent the typical weight range for women, while the other
represents the typical weight range for men. Since Bellabeat’s target
audience is women, this indicates that the dataset, which is from Fitbit
users, includes a significant number of male users.</li>
<li>The presence of two separate groups means that a single average
weight would be misleading and would not accurately represent either
group.</li>
</ul>
</div>
<div id="business-implication-bellabeat-15" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>This finding is critical for Bellabeat’s marketing and product
strategy because it highlights a key difference between the sample data
and their target audience.</li>
<li>Bellabeat’s marketing campaigns and product features should be
tailored specifically to women, as the current dataset’s insights may be
skewed by male user data.</li>
<li>The company should focus on creating content and product features
that resonate with the weight distribution and health goals of their
female users, represented by the first peak.</li>
</ul>
</div>
</div>
<div id="bmi-distributions-across-all-users" class="section level3">
<h3>BMI Distributions across All Users</h3>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a><span class="fu">ggplot</span>(weight_clean, <span class="fu">aes</span>(<span class="at">x =</span> bmi)) <span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>, <span class="at">fill=</span><span class="st">&quot;orange&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;BMI Distribution of Users&quot;</span>, <span class="at">x=</span><span class="st">&quot;BMI&quot;</span>, <span class="at">y=</span><span class="st">&quot;Number of Records&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<div id="finding-data-insight-16" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The histogram displays the distribution of BMI for the users in the
dataset.</li>
<li>The most frequent BMI values fall into the range of approximately 22
to 27.</li>
<li>The distribution is slightly right-skewed, with a longer tail
extending towards higher BMI values.</li>
<li>There are no data points in the “underweight” category (BMI below
18.5) and very few in the “obesity” categories (BMI of 30 or
greater).</li>
</ul>
</div>
<div id="interpretation-user-behavior-16" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>The majority of users in this sample have a BMI in the “healthy
weight” to “overweight” range. This indicates that the dataset’s users
are generally not underweight and are either at a healthy weight or are
carrying excess weight.</li>
<li>The right-skewed distribution suggests that while many users are at
a healthy weight, a significant portion is overweight, and a small
number of users are in the obese category.</li>
<li>This is a key insight because it shows that a large segment of the
potential customer base is likely interested in weight management and
health improvement, a core focus of Bellabeat’s products.</li>
</ul>
</div>
<div id="business-implication-bellabeat-16" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can target its marketing campaigns to the overweight
segment of the population. Messaging could focus on personalized weight
management goals, encouraging users to move from the “overweight”
category to the “healthy weight” category.</li>
<li>The company could develop new features or content within the
Bellabeat app specifically tailored to users with higher BMIs, such as
customized workout plans, nutritional guidance, and mindful eating
resources.</li>
</ul>
</div>
</div>
<div id="average-weight-and-bmi-over-time" class="section level3">
<h3>Average Weight and BMI Over Time</h3>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a>weight_clean <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a>  <span class="fu">group_by</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb49-4"><a href="#cb49-4" tabindex="-1"></a>    <span class="at">avg_weight =</span> <span class="fu">mean</span>(weight_kg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb49-5"><a href="#cb49-5" tabindex="-1"></a>    <span class="at">avg_bmi =</span> <span class="fu">mean</span>(bmi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb49-6"><a href="#cb49-6" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb49-7"><a href="#cb49-7" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(</span>
<span id="cb49-8"><a href="#cb49-8" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(avg_weight, avg_bmi),</span>
<span id="cb49-9"><a href="#cb49-9" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;Metric&quot;</span>,</span>
<span id="cb49-10"><a href="#cb49-10" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;Value&quot;</span></span>
<span id="cb49-11"><a href="#cb49-11" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb49-12"><a href="#cb49-12" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> Value, <span class="at">color =</span> Metric)) <span class="sc">+</span></span>
<span id="cb49-13"><a href="#cb49-13" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb49-14"><a href="#cb49-14" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb49-15"><a href="#cb49-15" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Average Weight and BMI Over Time&quot;</span>,</span>
<span id="cb49-16"><a href="#cb49-16" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb49-17"><a href="#cb49-17" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb49-18"><a href="#cb49-18" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Metric&quot;</span></span>
<span id="cb49-19"><a href="#cb49-19" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb49-20"><a href="#cb49-20" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(</span>
<span id="cb49-21"><a href="#cb49-21" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;avg_weight&quot;</span> <span class="ot">=</span> <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;avg_bmi&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>),</span>
<span id="cb49-22"><a href="#cb49-22" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;avg_weight&quot;</span> <span class="ot">=</span> <span class="st">&quot;Average Weight (kg)&quot;</span>, <span class="st">&quot;avg_bmi&quot;</span> <span class="ot">=</span> <span class="st">&quot;Average BMI&quot;</span>)</span>
<span id="cb49-23"><a href="#cb49-23" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb49-24"><a href="#cb49-24" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bellabeat_markdown_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div id="finding-data-insight-17" class="section level4">
<h4>Finding (Data Insight)</h4>
<ul>
<li>The graph displays two metrics: Average Weight (in kg) and Average
BMI.</li>
<li>The Average BMI line (red) remains relatively stable, hovering
around a value of 25.</li>
<li>The Average Weight line (blue) shows significant fluctuation over
the period, with values swinging between approximately 60 kg and 85
kg.</li>
</ul>
</div>
<div id="interpretation-user-behavior-17" class="section level4">
<h4>Interpretation (User Behavior)</h4>
<ul>
<li>The average BMI values fall near the healthy-overweight threshold of
25, which aligns with a previous finding that the average BMI of the
users is 25.4.</li>
<li>The wide fluctuations in the average weight suggest that weight
logging among this small group of users is inconsistent. It’s likely
that a few users with very high or low weights are logging their data
sporadically, causing the average to swing dramatically.</li>
<li>While the average BMI remains relatively stable, the volatility of
the weight data could be discouraging for a user trying to track their
progress.</li>
</ul>
</div>
<div id="business-implication-bellabeat-17" class="section level4">
<h4>Business Implication (Bellabeat)</h4>
<ul>
<li>Bellabeat can implement features that encourage consistent, daily
weight logging to provide users with a more stable and accurate
long-term trend.</li>
<li>The app could offer educational content that explains the difference
between short-term weight fluctuations and long-term trends, helping
users understand their data better.</li>
<li>Given that the average BMI is in the overweight range, Bellabeat can
develop targeted in-app programs or challenges focused on healthy weight
management, combining activity goals with nutritional tips.</li>
</ul>
</div>
</div>
</div>
<div id="act" class="section level2">
<h2>🎯 Act</h2>
<p>The insights gathered from the data reveal that users have a moderate
but inconsistent engagement with health tracking, often falling into a
“sleep debt” pattern on weekends and having an average BMI in the
overweight range. The Bellabeat App can serve as the primary tool to
address these user behaviors through targeted features and a refined
marketing strategy.</p>
<div id="product-development-features" class="section level4">
<h4>1. Product Development &amp; Features</h4>
<ul>
<li><p><strong>Implement a Sleep Debt Tracker and Alert System</strong>:
The app should track the difference between weekday and weekend sleep.
When a significant gap is detected, the app can send a personalized
alert to the user, reminding them to maintain a more consistent sleep
schedule.</p></li>
<li><p><strong>Integrate Gamified “Streak Challenges”</strong>: To
combat the periodic dips in activity, introduce a “Consistency
Challenge” that encourages users to maintain a minimum of 7,000 steps
for seven consecutive days. Offer badges or small rewards for reaching
milestones.</p></li>
<li><p><strong>Enhance Health Dashboards</strong>: Create a dashboard
that visualizes a user’s progress on key metrics like BMI and weight
over time. This can help users who are gaining or losing weight to
visualize their trends and stay motivated.</p></li>
<li><p><strong>Develop a Holistic Health Score</strong>: The app can use
data points such as steps, sleep efficiency, and activity intensity to
generate a single “Daily Health Score”. This simplified metric would
help users understand their overall wellness and encourage them to
improve low-scoring areas.</p></li>
</ul>
</div>
<div id="marketing-communication" class="section level4">
<h4>2. Marketing &amp; Communication</h4>
<ul>
<li><p><strong>Launch a “Find Your Healthy” Campaign</strong>: The
average user has a BMI in the overweight range, but a relatively healthy
body fat percentage. Bellabeat’s marketing can focus on this,
emphasizing that true health is more than just a number on the
scale.</p></li>
<li><p><strong>Create Targeted Nudges</strong>: Instead of
one-size-fits-all messages, the app should provide targeted alerts. For
example, a reminder to “get moving” at 4 p.m. to encourage evening
activity, which is a peak time for users.</p></li>
<li><p><strong>Emphasize Education</strong>: Provide educational content
within the app that explains the combined impact of steps, intensity,
and duration on calorie burn. This will help users understand how to get
the most out of their activity and support healthier outcomes.</p></li>
</ul>
</div>
<div id="strategy-positioning" class="section level4">
<h4>3. Strategy &amp; Positioning</h4>
<ul>
<li><p><strong>Position Bellabeat as a Proactive Partner</strong>:
Position Bellabeat not just as a data logger, but as a personal wellness
coach. The app’s features for sleep debt alerts and tailored nudges
demonstrate a proactive approach to a user’s well-being.</p></li>
<li><p><strong>Align with Long-Term Habits</strong>: Focus on promoting
sustainable, long-term habits rather than short-term gains. By
encouraging a consistent 5,000–10,000 steps per day, Bellabeat can help
users maintain a healthy routine</p></li>
</ul>
</div>
</div>
<div id="main-insights-summary" class="section level2">
<h2>📝 Main Insights Summary</h2>
<p>Here is a summary of the main insights derived from the analysis of
the Fitbit data, covering key findings from all analyzed datasets:</p>
<ul>
<li><p><strong>Daily Activity</strong>: There is a strong, positive
correlation between the number of steps taken and the calories burned.
Users’ activity levels are generally consistent throughout the week,
with slight peaks on Tuesdays and Saturdays and the lowest activity on
Sundays. The average daily step count is below the recommended 10,000
steps.</p></li>
<li><p><strong>Hourly Activity</strong>: User activity shows two
distinct peaks during the day: a morning peak and a more significant
evening peak (5 p.m. to 8 p.m.). This pattern suggests that users are
most active before and after a standard workday.</p></li>
<li><p><strong>Sleep Patterns</strong>: Users tend to accumulate a
“sleep debt” during the weekdays, which they try to make up for on
weekends by sleeping longer. This inconsistency in sleep habits presents
an opportunity for Bellabeat to offer features that promote better sleep
routines.</p></li>
<li><p><strong>Weight and BMI</strong>: The average BMI of the user
population falls into the overweight category. However, since the data
also suggests a healthy body fat percentage for many users, Bellabeat
can emphasize that overall wellness is more important than just a number
on the scale.</p></li>
<li><p><strong>Device Usage</strong>: The dataset has a limited number
of users, and the data is from a small subset of the population, which
may not be representative of Bellabeat’s target audience of
women.</p></li>
</ul>
</div>
<div id="data-limitations" class="section level2">
<h2>⚠️ Data Limitations:</h2>
<ul>
<li><p><strong>Limited Timeframe</strong>: The dataset is too limited in
duration, as it only covers a period of 60 days, and many of the
individual files only have 30 days of data. This short timeframe makes
it difficult to identify long-term trends or seasonal patterns.</p></li>
<li><p><strong>Insufficient Demographic Data</strong>: The dataset lacks
crucial demographic information such as gender, age, and location. This
is a significant limitation, especially since Bellabeat’s target
audience is women. Without this data, the insights cannot be
definitively applied to Bellabeat’s specific user base.</p></li>
<li><p><strong>Small Sample Size</strong>: The dataset is derived from a
small sample of only 30 users, making the findings difficult to
generalize to the broader population of fitness tracker users.</p></li>
<li><p><strong>Non-representative population</strong>: Fitbit
participants are not Bellabeat users</p></li>
<li><p><strong>Incomplete Logs</strong>: Not all users recorded sleep
and weight consistently</p></li>
<li><p><strong>Outdated</strong>: Data collected in 2016, which is
outdated to current behaviors</p></li>
</ul>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
